export const WORD_BANKS = {
  en: [
    'the', 'be', 'to', 'of', 'and', 'a', 'in', 'that', 'have', 'it',
    'for', 'not', 'on', 'with', 'he', 'as', 'you', 'do', 'at', 'this',
    'but', 'his', 'by', 'from', 'they', 'we', 'say', 'her', 'she', 'or',
    'an', 'will', 'my', 'one', 'all', 'would', 'there', 'their', 'what',
    'so', 'up', 'out', 'if', 'about', 'who', 'get', 'which', 'go', 'me',
    'when', 'make', 'can', 'like', 'time', 'no', 'just', 'him', 'know',
    'take', 'people', 'into', 'year', 'your', 'good', 'some', 'could',
    'them', 'see', 'other', 'than', 'then', 'now', 'look', 'only',
    'come', 'its', 'over', 'think', 'also', 'back', 'after', 'use',
    'two', 'how', 'our', 'work', 'first', 'well', 'way', 'even', 'new',
    'want', 'because', 'any', 'these', 'give', 'day', 'most', 'us',
    'great', 'between', 'need', 'large', 'under', 'never', 'city',
    'tree', 'water', 'long', 'find', 'here', 'thing', 'many', 'still',
    'high', 'every', 'name', 'keep', 'should', 'home', 'big', 'hand',
    'life', 'place', 'where', 'next', 'old', 'while', 'last', 'right',
    'start', 'might', 'begin', 'those', 'side', 'same', 'world', 'help',
    'line', 'turn', 'move', 'live', 'real', 'left', 'point', 'read',
    'often', 'run', 'head', 'play', 'small', 'set', 'change', 'off',
    'much', 'before', 'why', 'kind', 'each', 'tell', 'does', 'land',
    'page', 'letter', 'show', 'try', 'close', 'group', 'open', 'own',
    'learn', 'end', 'above', 'below', 'power', 'music', 'paper', 'food',
    'part', 'plant', 'best', 'light', 'story', 'study', 'room', 'young',
    'house', 'table', 'early', 'money', 'three', 'being', 'body', 'state',
    'river', 'south', 'north', 'hard', 'near', 'face', 'form', 'number',
    'again', 'once', 'book', 'sound', 'build', 'along', 'very', 'write',
    'word', 'black', 'white', 'round', 'field', 'class', 'clear', 'rock',
    'force', 'sure', 'done', 'front', 'hold', 'step', 'plan', 'fast',
    'mind', 'dream', 'green', 'earth', 'cover', 'order', 'voice',
    'system', 'level', 'cross', 'spend', 'press', 'fire', 'watch',
    'reach', 'rest', 'speak', 'human', 'space', 'month', 'drive',
    'check', 'stand', 'model', 'woman', 'bring', 'heat', 'warm', 'free',
    'moment', 'happy', 'exist', 'chair', 'fish', 'simple', 'window',
    'strong', 'care', 'final', 'cool', 'dark', 'deep', 'sense', 'ball',
    'train', 'child', 'night', 'heart', 'short', 'piece', 'glass',
    'horse', 'mountain', 'answer', 'travel', 'center', 'half', 'ten',
    'several', 'against', 'during', 'hundred', 'ocean', 'island'
  ],
  id: [
    'dan', 'di', 'yang', 'ini', 'itu', 'dengan', 'untuk', 'pada',
    'adalah', 'dari', 'dalam', 'akan', 'tidak', 'bisa', 'ada', 'juga',
    'saya', 'kita', 'kami', 'mereka', 'dia', 'anda', 'kalian', 'kamu',
    'sudah', 'belum', 'sedang', 'telah', 'masih', 'harus', 'baru',
    'satu', 'dua', 'tiga', 'empat', 'lima', 'enam', 'tujuh', 'delapan',
    'sembilan', 'sepuluh', 'ratus', 'ribu', 'juta', 'pertama', 'kedua',
    'waktu', 'hari', 'bulan', 'tahun', 'pagi', 'siang', 'sore', 'malam',
    'rumah', 'sekolah', 'kantor', 'kota', 'desa', 'jalan', 'pintu',
    'makan', 'minum', 'tidur', 'bangun', 'duduk', 'berdiri', 'jalan',
    'lari', 'baca', 'tulis', 'bicara', 'dengar', 'lihat', 'rasa',
    'besar', 'kecil', 'tinggi', 'rendah', 'panjang', 'pendek', 'lebar',
    'berat', 'ringan', 'cepat', 'lambat', 'banyak', 'sedikit', 'semua',
    'baik', 'buruk', 'bagus', 'indah', 'cantik', 'tampan', 'pintar',
    'bodoh', 'kuat', 'lemah', 'muda', 'tua', 'baru', 'lama', 'dekat',
    'jauh', 'dalam', 'luar', 'atas', 'bawah', 'depan', 'belakang',
    'kanan', 'kiri', 'tengah', 'samping', 'antara', 'sekitar', 'selalu',
    'air', 'api', 'tanah', 'angin', 'hujan', 'panas', 'dingin', 'terang',
    'gelap', 'putih', 'hitam', 'merah', 'biru', 'hijau', 'kuning',
    'orang', 'anak', 'ibu', 'ayah', 'kakak', 'adik', 'teman', 'guru',
    'dokter', 'petani', 'nelayan', 'polisi', 'tentara', 'raja', 'rakyat',
    'negara', 'bangsa', 'dunia', 'tanah', 'laut', 'gunung', 'sungai',
    'hutan', 'pantai', 'pulau', 'danau', 'langit', 'bintang', 'bulan',
    'matahari', 'awan', 'pelangi', 'bunga', 'pohon', 'daun', 'buah',
    'buku', 'kertas', 'pena', 'meja', 'kursi', 'papan', 'komputer',
    'telepon', 'mobil', 'motor', 'kapal', 'pesawat', 'kereta', 'sepeda',
    'uang', 'harga', 'pasar', 'toko', 'beli', 'jual', 'bayar', 'murah',
    'mahal', 'untung', 'rugi', 'kerja', 'usaha', 'hasil', 'sukses',
    'gagal', 'coba', 'mulai', 'selesai', 'berhenti', 'lanjut', 'ulang',
    'tahu', 'pikir', 'ingat', 'lupa', 'belajar', 'ajar', 'latih',
    'bantu', 'tolong', 'terima', 'kasih', 'maaf', 'silakan', 'selamat',
    'senang', 'sedih', 'marah', 'takut', 'berani', 'sabar', 'sayang',
    'cinta', 'rindu', 'harap', 'percaya', 'yakin', 'ragu', 'benar',
    'salah', 'betul', 'tepat', 'pasti', 'mungkin', 'tentu', 'hampir',
    'sangat', 'cukup', 'terlalu', 'kurang', 'lebih', 'paling', 'agak',
    'hanya', 'justru', 'bahkan', 'namun', 'tetapi', 'karena', 'sebab',
    'supaya', 'agar', 'jika', 'kalau', 'ketika', 'sambil', 'setelah',
    'sebelum', 'selama', 'hingga', 'sampai', 'sejak', 'seperti', 'begitu',
    'makanan', 'minuman', 'pakaian', 'sepatu', 'topi', 'cincin', 'kalung',
    'suara', 'musik', 'lagu', 'cerita', 'gambar', 'warna', 'bentuk'
  ]
};

export const CODE_TO_KEY = {
  'Backquote': '`', 'Digit1': '1', 'Digit2': '2', 'Digit3': '3',
  'Digit4': '4', 'Digit5': '5', 'Digit6': '6', 'Digit7': '7',
  'Digit8': '8', 'Digit9': '9', 'Digit0': '0', 'Minus': '-',
  'Equal': '=', 'Backspace': 'Backspace',
  'Tab': 'Tab',
  'KeyQ': 'q', 'KeyW': 'w', 'KeyE': 'e', 'KeyR': 'r', 'KeyT': 't',
  'KeyY': 'y', 'KeyU': 'u', 'KeyI': 'i', 'KeyO': 'o', 'KeyP': 'p',
  'BracketLeft': '[', 'BracketRight': ']', 'Backslash': '\\',
  'CapsLock': 'CapsLock',
  'KeyA': 'a', 'KeyS': 's', 'KeyD': 'd', 'KeyF': 'f', 'KeyG': 'g',
  'KeyH': 'h', 'KeyJ': 'j', 'KeyK': 'k', 'KeyL': 'l',
  'Semicolon': ';', 'Quote': "'", 'Enter': 'Enter',
  'ShiftLeft': 'ShiftLeft',
  'KeyZ': 'z', 'KeyX': 'x', 'KeyC': 'c', 'KeyV': 'v', 'KeyB': 'b',
  'KeyN': 'n', 'KeyM': 'm',
  'Comma': ',', 'Period': '.', 'Slash': '/',
  'ShiftRight': 'ShiftRight',
  'ControlLeft': 'ControlLeft', 'AltLeft': 'AltLeft',
  'Space': ' ',
  'AltRight': 'AltRight', 'ControlRight': 'ControlRight',
};
