export const dom = {
  textDisplay: document.getElementById('textDisplay'),
  timerDisplay: document.getElementById('timerDisplay'),
  wpmDisplay: document.getElementById('wpmDisplay'),
  accuracyDisplay: document.getElementById('accuracyDisplay'),
  charsDisplay: document.getElementById('charsDisplay'),
  hintText: document.getElementById('hintText'),
  langSelector: document.getElementById('langSelector'),
  timerSelector: document.getElementById('timerSelector'),
  keyboard: document.getElementById('virtualKeyboard'),
  typingArea: document.getElementById('typingArea'),
  keyboardSection: document.getElementById('keyboardSection'),
  resultSection: document.getElementById('resultSection'),
  resultWpm: document.getElementById('resultWpm'),
  resultAccuracy: document.getElementById('resultAccuracy'),
  resultCorrect: document.getElementById('resultCorrect'),
  resultWrong: document.getElementById('resultWrong'),
  resultTime: document.getElementById('resultTime'),
  resultChart: document.getElementById('resultChart'),
  restartBtn: document.getElementById('restartBtn'),
  difficultyCustomSelect: document.getElementById('difficultyCustomSelect'),
  difficultySelected: document.getElementById('difficultySelected'),
  difficultyOptions: document.getElementById('difficultyOptions'),
  speedBadge: document.getElementById('speedBadge'),
  themeToggle: document.getElementById('themeToggle'),
};
